### ISSUE TITLE
ERROR:lint:invalid rule: rules/lib/peb-access.yml: invalid rule: unexpected statement: offset/x32

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#1011]
rules and code need to be lined up (again)

**Comment by williballenthin** [comment]
how do you propose to fix this?

**Comment by mr-tz** [comment]
Good question! I'm very confused with the current code vs. rule compatibility.

**Comment by williballenthin** [comment]
capa master:
  - adds `instruction scope`
  - removes `/x32` flavors

capa-rules master: targets v3 release of capa
  - uses `/x32` because there is no `instruction` scope

capa-rules v4-dev: targets upcoming v4 release of capa
  - no `/x32` references
  - uses `instruction` scope

basically, we cannot use capa master with capa-rules master because there are both forwards and backwards breaking changes. capa devs should probably track v4-dev.

**Comment by mr-tz** [comment]
We should get a new release out ASAP.

In the meantime, to not hinder further dev and burden our users:
1. remove x32/x64 from rules: https://github.com/mandiant/capa-rules/tree/fix/temp-remove-x32-x64-flavors
OR
2. ignore x32/x64 during rule parsing: https://github.com/mandiant/capa/tree/fix/temp-accept-x32-x64-but-ignore

I prefer 2. because it's easy to undo. Downside on both: potentially more FPs while this is not fixed.

**Comment by williballenthin** [comment]
fixed in #1014
