### ISSUE TITLE
Strings include or don't include `\r\n`

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#1277]
1. In `capa/features/extractors/strings.py` we do not extract `\r\n` so this seems inconsistent between file and instruction scope?

Should we make this uniform across the extractors or keep as is (since we have more knowledge at the instruction scope, for example)?

_Originally posted by @mr-tz in https://github.com/mandiant/capa/pull/1273#discussion_r1065491133_

**Comment by williballenthin** [comment]
at the instruction scope it might be nice to support newlines so we can match things like full HTTP request + headers.

at the file scope, tools like strings typically split on newline because its easier to render the output this way.

i think keeping newlines is more "correct" but someone please convince me otherwise!

**Comment by mr-tz** [comment]
This makes sense. Leaving as is an we can refer to this issue here if this comes up in the future.
