### ISSUE TITLE
IDA explorer: persist results across runs

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#1279]
Is it worth storing results once the plugin ran so we can load it without doing the same work again in a subsequent run?

**Comment by r0ny123** [comment]
+1 for this. It would save a lot of time!

**Comment by williballenthin** [comment]
we could store data into a netnode within the idb so its persisted within the workspace.

concern: are there common analysis operations that would invalidate the features extracted by capa? e.g. unpacking or changing memory, renaming functions, etc.? is this mitigated by having the "analyze" button easily accessible to re-run the analysis?

**Comment by mr-tz** [comment]
I meant this use case:
> opening IDA, running capa explorer, closing IDA, and then opening IDA again where capa explorer must be run again

I think the analyze button mitigates invalid/missing hits. Especially, if we add clear indication on what is being displayed (cached results) and these may be outdated (after certain events like mentioned above).

**Comment by mike-hunhoff** [comment]
> I meant this use case:
> 
> > opening IDA, running capa explorer, closing IDA, and then opening IDA again where capa explorer must be run again
> 
> I think the analyze button mitigates invalid/missing hits. Especially, if we add clear indication on what is being displayed (cached results) and these may be outdated (after certain events like mentioned above).

I think it makes sense to cache the results as @williballenthin suggested to address your use case @mr-tz .

As part of this impl. we'd likely want to:

- [ ] verify capa explorer can handle stale references e.g. what happens if user double-clicks an address in the UI that no long exists
  - [ ] prompt user to re-run analysis e.g. like we do after a program rebase? 
- [ ] add indication that capa explorer is using cached results that could be stale
  - [ ] initial prompt containing the warning (least favorite, I'm in favor of less popups but this is the most likely solution to ensure user sees our warning)
  - [ ] included in status message already displayed in lower left UI (possible user doesn't notice it) 
- [ ] see if we can force IDA to keep the capa explorer window open after IDA is restarted e.g. like the decompiler window; this would be especially useful if we cache previous run results

**Comment by mr-tz** [comment]
I've talked to another analyst today who does NOT run capa explorer every time, because it requires manual reprocessing and forces a wait.

**Comment by mr-tz** [comment]
> see if we can force IDA to keep the capa explorer window open after IDA is restarted e.g. like the decompiler window; this would be especially useful if we cache previous run results

I did not find an option or example to make plugins persist like this.

There is an `AUTORUN_PLUGINS` in ida.cfg, but that only appears to load native plugins.

As a workaround, we may be able to load the plugin via an entry in `idapythonrc.py`, but there may be timing issues, e.g., when does this run vs. when the plugin is available.

**Comment by HongThatCong** [comment]
This is a feature I have wanted for a long time from the capa explorer IDA plugin.
I've been thinking of writing my own but haven't had the time and thought of a way to save the analysis tree results to json.
I agree with william's comments.
1. Save analysis results to json -> pickle -> netnode, as FunctionScanner did.
https://github.com/patois/FuncScanner
2. When the user wants to run the plugin again, check whether the analysis results have been saved first or not?
3. If yes, ask the user if he wants to show the previous results or rescan?
4. If the user wants to scan again, do the same job as the user who clicked the analysis button
A few comments.
Tks

**Comment by mr-tz** [comment]
Thanks, that is helpful. I have a POC working and hope to get something up for review in the next few days.

**Comment by HongThatCong** [comment]
Great work, Moritz

**Comment by mr-tz** [comment]
@r0ny123 and @HongThatCong please see the most recent code. Would be great if you can test drive and provide some brief feedback if things are working or not.

**Comment by r0ny123** [comment]
I just tested the latest capa and the feature works like a charm! Thanks, @mr-tz 🙏.

**Comment by mr-tz** [comment]
Amazing, thanks for the feedback!
