### ISSUE TITLE
consider using deptry to review dependencies

### ISSUE THREAD

**Issue by williballenthin** [mandiant/capa#1497]
https://github.com/fpgmaas/deptry

**Comment by psahithireddy** [comment]
Hello, can I take this up. I have read a bit about deptry and its [rule violations](https://fpgmaas.github.io/deptry/rules-violations/). This repo has multiple DEP001, DEP002 and DEP003 errors.
- Few of DEP001 are due to module imports which need not be added to dev dependencies, hence we can add for deptry ignore in toml file (like ghidra, binaryninja), others (ids, java) I am investigating if its module or missing dependency. 
- DEP002 is due to formatting and checking modules (flake8, isort, ruff) that needs to added to ignore file, as deptry only checks  imports py, ipynb files.
-  I am still reading about DEP003 and how to resolve/ignore it.

**Comment by mr-tz** [comment]
Sounds good, go for it 😄
