### ISSUE TITLE
figure out how to represent "event address" for dynamic analysis extractors

### ISSUE THREAD

**Issue by ghost** [mandiant/capa#1544]
today, we have an "Address" abstraction that represents the location of a feature within a file thats used by the static analysis flavor extractor/engine/renderer.

we need to figure out how to represent the event id, probably as an Address, for use in the dynamic analysis flavor.

something like (PID, TID, event index) might work, but other options are acceptable, too.

**Comment by mr-tz** [comment]
Including the return address (e.g. `"caller": "0x00cef81f",` in the CAPE JSON) may help to identify addresses as well.

**Comment by williballenthin** [comment]
i wonder if the purpose of this address is:

  1. to identify the event in the sandbox report, such that the user can quickly navigate to that entry in the report, or
  2. to identify the location in the program, such that the user can open up a disassembler and see the logic.

my intuition is that its (1) that we might want, since there might be multiple calls/events at the same address (such as within a loop) with different arguments. but given that (2) is a likely workflow, maybe we can incorporate that information as well?

**Comment by mr-tz** [comment]
I think we can do both. There's
* the `id` field to identify the location in the JSON and
* the `caller` to (potentially) find the return address in a disassembler.

**Comment by williballenthin** [comment]
this was addressed by @yelhamer in their ongoing dynamic analysis branch
