### ISSUE TITLE
website: configure GH Actions to build and deploy website

### ISSUE THREAD

**Issue by ghost** [mandiant/capa#1553]

**Comment by DeeyaSingh** [comment]
Implemented a GitHub Actions workflow to automate building and deployment of the capa website. The workflow triggers on every push to the main branch or can be manually started. It checks out our repository, sets up Ruby, builds the Jekyll site, and deploys the site to GitHub Pages.

**Comment by williballenthin** [comment]
this is a nice implementation. i like that the website is rebuilt upon each change to the repository.

i think we should consider adding the rules as a git submodule, rather than copying in the rule content. this way, we can easily update the rule set and avoid having multiple copies of the rule content in different places.

**Comment by DeeyaSingh** [comment]
Using the rules as a git submodule makes a lot of sense and, would eliminate the redundancy of having multiple copies. I'm not entirely familiar with implementing it this way, but I'm definitely interested in exploring the possibility. I'll look into how we can integrate the rules as a git submodule and ensure that the content remains easily updatable

**Comment by williballenthin** [comment]
closed in #2264
