### ISSUE TITLE
webui: should the webui live in its own repo or here?

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#2192]
Leaning towards a separate repo but open to discussion.

Edit: after further discussion let's start in this repo and reevaluate then, only if it doesn't feel right we should consider creating a new repo just for the webui rendering code

**Comment by williballenthin** [comment]
Let's start by maintaining the webui in the primary capa repository. Two options come to mind:

  1. in a subdirectory of the `./docs/` directory, and
  2. in a branch with no shared history with `main`.

Initially I was leaning towards (2), because it keeps the work somewhat isolated. However, I'm not sure that this will work great with the github UI and might be confusing to potential contributors.

I'm leaning towards (1) now. While it may introduce more content within the capa repository, particularly mixing python, js, html, css in one repo, it's simpler and more obvious. Of course, we should never check in generated content into the repository, such as built javascript bundles or rendered capa rules, so all the things we do check in should be real content/code.

**Comment by williballenthin** [comment]
cc @DeeyaSingh for the final resting place of your capa rules web interface code.

**Comment by s-ff** [comment]
I just opened a new PR in upstream/webui, as you mentioned this keep the Python/JS code seperate, but the two branches need to be synced priodically somehow? 

This Github Action does this: https://github.com/marketplace/actions/sync-branches

**Comment by s-ff** [comment]
Decided on keeping work as part of this repo. Code will live in root `./web/` in `./web/results` (instead of `./webui`).

Closed as completed.
