### ISSUE TITLE
Introduce select checkboxes to the tree similar to PyQt5 capa-explorer

### ISSUE THREAD

**Issue by mike-hunhoff** [mandiant/capa#2200]
I'm not sure what the benefit of adding these checkboxes to the webui? The PyQt5 capa-explorer uses this feature to highlight addresses in the listing view but we don't have that in the webui...

**Comment by s-ff** [comment]
Good question, @mike-hunhoff. This was raised by others as well.

I introduced checkboxes for a simple reason: readability. Sometimes rules have deep nested branches and tracking them visually can be challenging. That's why I think these checkboxes than can help in highlighting to which branch a particular node belong to. For example, we can toggle an `and` branch which would highlight (toggle) all the lower nodes that belong to it leaving other unhighlighted.

To eliminate user confusion, I believe we should make this optional and users can toggle it on/off, or remove it entirely. What do you think?

**Comment by mike-hunhoff** [comment]
Do we have other options for making it easier visually to track the nesting? e.g. using lines to connect the nested branches?

**Comment by s-ff** [comment]
Unfortunaltey this is not natively supported and requires manual tweaking. I have already started expirementing with this, though it is not perfect. [See example](https://stackblitz.com/edit/isbcyq?file=src%2FApp.vue).

**Comment by s-ff** [comment]
> Are the boxes natively supported or is this a custom implementation?

They are supported by default

**Comment by s-ff** [comment]
Removed checkboxes.
