### ISSUE TITLE
Feature: call $+5

### ISSUE THREAD

**Issue by mr-tz** [mandiant/capa#366]
### Summary

Add (one-off) feature to match on `call    $+5`; often used in shellcode or for obfuscation.

### Motivation

Help to detect shellcode and anti-disassembly techniques.

**Comment by kn0wl3dge** [comment]
Hi @mr-tz ,
I am currently looking into capa internals.
If I understand correctly capa code, this could be solved by adding functions that extract `Characteristic("call $+5")` inside the capa extractors.
What should be the "scope" for this? I think this feature could be extracted at a *basic block* level or at an *instruction* level. Is there a preferred option (that could be related to performance for example)?

**Comment by williballenthin** [comment]
I think this should be extracted at instruction scope, like how fs/gs access is extracted.

There's potentially a minor performance difference, but I think without profiling results that show this is a bottleneck, we should use Instruction scope when appropriate.

**Comment by kn0wl3dge** [comment]
All right, I should be able to start working on this in the next few days. 
Feel free to assign me this issue.

**Comment by mr-tz** [comment]
Sounds great. Thank you! We're happy to help with any questions.

**Comment by kn0wl3dge** [comment]
Hi,
I started working on this using the capa rule [64-bit execution via heavens gate](https://github.com/mandiant/capa-rules/blob/master/anti-analysis/anti-disasm/64-bit-execution-via-heavens-gate.yml) to find an example where this feature should be extracted.

However, I am obtaining different results on this binary depending on the backend. I am using the test sample `79abd17391adc6251ecdc58d13d76baf.dll_`.   

With smda:
```bash
python3 scripts/show-features.py -b smda tests/data/79abd17391adc6251ecdc58d13d76baf.dll_ | grep 'call $+5'
insn: 0x10002396: characteristic(call $+5)
insn: 0x100023cd: characteristic(call $+5)
```

With vivisect:
```bash
python3 scripts/show-features.py -b vivisect tests/data/79abd17391adc6251ecdc58d13d76baf.dll_ | grep 'call $+5'
insn: 0x10002396: characteristic(call $+5)
```

I'm guessing from the few tests I made that vivsect is not disassembling the code around *0x100023cd*.  
To look further I would need other samples using this obfuscation technique.
@williballenthin @mr-tz Do you guys have in mind few more binaries using this obfuscation technique?

Also, I think that I won't be able to add the IDA extractor since it requires IDA Pro (from what I understood).

**Comment by mr-tz** [comment]
Awesome, thanks for looking into this!

In the test files I could locate this file:
`946a99f36a46d335dec080d9a4371940.dll_:0x100015C7`

On Virustotal I found the following (packed) files (attached with password infected [call5.zip](https://github.com/mandiant/capa/files/8108185/call5.zip)):
`5b1102b10f8d0dee41b592bea0892ac78cecee1a3f5bc55c5176359634c6c002`
`efbf3f3546130f3a00304eb1873fb0b72b27988f162f5599024e49b3df864f2a`
`f99c836e89a6a181d292e1aad24d8667c6b53b870548dada3694e474b259d3e9`

I hope that helps a bit. Please let me know otherwise.

We can add the IDA extractor, if you don't have IDAPython available.

**Comment by kn0wl3dge** [comment]
So I made further test and it seems that the issue comes from vivisect or smda not being able to disassemble the code.
As example, here's the output of vivisect for the test sample `79abd17391adc6251ecdc58d13d76baf.dll_`:

<img width="701" alt="Vivisect output" src="https://user-images.githubusercontent.com/17934627/155887100-0d82f2d2-5c29-46d4-b65d-2752a6d44318.png">

As you can see, the `0x100023cd: characteristic(call $+5)` cannot be extracted with vivisect because it did not disassemble this part of the memory.

I also made some test on the other binary you provided and got these kinds of results:
```
❯ python3 scripts/show-features.py -b smda  ~/Downloads/call5/efbf3f3546130f3a00304eb1873fb0b72b27988f162f5599024e49b3df864f2a | grep 'call'

❯ python3 scripts/show-features.py -b vivisect  ~/Downloads/call5/efbf3f3546130f3a00304eb1873fb0b72b27988f162f5599024e49b3df864f2a | grep 'call'
insn: 0x004241b4: mnemonic(call)
insn: 0x004241b4: characteristic(call $+5)
insn: 0x004241b9: characteristic(calls from)
insn: 0x00424223: mnemonic(call)
insn: 0x00424286: characteristic(calls from)
insn: 0x00424261: mnemonic(call)
insn: 0x00424261: characteristic(call $+5)
insn: 0x00424266: characteristic(calls from)
insn: 0x00424276: mnemonic(call)
insn: 0x00424276: characteristic(call $+5)
insn: 0x0042427b: characteristic(calls from)
func: 0x00424223: characteristic(calls to)
func: 0x00424223: characteristic(calls to)
```

So I think that it is not really an issue as rule matching and feature extraction can be different depending on the backend used.

**Comment by mr-tz** [comment]
Thank you, @kn0wl3dge!
